test: Report error before exiting.

diff --git a/test.sh.in b/test.sh.in
--- a/test.sh.in
+++ b/test.sh.in
@@ -5,7 +5,9 @@ export PIGX_BSSEQ_UNINSTALLED=1
 ./pigx_bs test/Tablesheet.txt
 
 for base in PEsample_1_val_1_bt2 SEsample_se_bt2 SEsample_v2_se_bt2; do
-    test -f "test/out/final_Report/${base}.deduped.sorted_hg19_final.nb.html" || exit 1
+    if ! test -f "test/out/final_Report/${base}.deduped.sorted_hg19_final.nb.html"
+    then
+        echo "ERROR: could not find report for ${base}"
+        exit 1
+    fi
 done
-
-
