replace tests for star with tests for  hisat2

diff --git a/tests/test_hisat2/test.sh.in b/tests/test_hisat2/test.sh.in
--- a/tests/test_hisat2/test.sh.in
+++ b/tests/test_hisat2/test.sh.in
@@ -30,14 +30,14 @@ samplesheet=${srcdir}/tests/sample_sheet.csv
 tmp_samplesheet=${testfolder}/sample_sheet.test_star.csv
 head -n 2 ${samplesheet} > ${tmp_samplesheet}
 
-${builddir}/pigx-rnaseq -s ${tmp_settings} --target star_map ${tmp_samplesheet}
+${builddir}/pigx-rnaseq -s ${tmp_settings} --target hisat2_map ${tmp_samplesheet}
 
 rm ${tmp_settings} ${tmp_samplesheet}
 
 rm -rf ${testfolder}/trimmed_reads
 
-if ! test -f ${testfolder}/mapped_reads/HBR_Rep1_Aligned.sortedByCoord.out.bam
+if ! test -f ${testfolder}/mapped_reads/hisat2/HBR_Rep1_Aligned.sortedByCoord.out.bam
 then
-  echo "ERROR: failed the STAR mapping test"
+  echo "ERROR: failed the HISAT2 mapping test"
   exit 1
 fi
diff --git a/tests/test_hisat2_counts/test.sh.in b/tests/test_hisat2_counts/test.sh.in
--- a/tests/test_hisat2_counts/test.sh.in
+++ b/tests/test_hisat2_counts/test.sh.in
@@ -4,7 +4,7 @@ set -e
 set -u
 
 root=$(mktemp --tmpdir -d "pigx.XXXX")
-testfolder=${root}/tests/test_star_counts
+testfolder=${root}/tests/test_hisat2_counts
 mkdir -p ${testfolder}
 
 echo "TEST FOLDER: ${testfolder}"
@@ -28,14 +28,14 @@ sed -e "s,reads-dir: ,reads-dir: ${srcdir}/tests/,g" \
 
 samplesheet=${srcdir}/tests/sample_sheet.csv
 
-${builddir}/pigx-rnaseq -s ${tmp_settings} --target star_counts ${samplesheet}
+${builddir}/pigx-rnaseq -s ${tmp_settings} --target hisat2_counts ${samplesheet}
 
 rm ${tmp_settings}
 
 rm -rf ${testfolder}/mapped_reads/
 
-if ! test -f ${testfolder}/feature_counts/raw_counts/counts_from_star.tsv
+if ! test -f ${testfolder}/feature_counts/raw_counts/hisat2/counts.tsv
 then
-  echo "ERROR: failed obtaining counts matrix from STAR results"
+  echo "ERROR: failed obtaining counts matrix from hisat2 results"
   exit 1
 fi
